relay {
    bind = "0.0.0.0"
    port = 7777
    serviceUrl = "ws://localhost:7777"
    whitelistedPubkeys = "6b5008a293291c14effeb0e8b7c56a80ecb5ca7b801768e17ec93092be6c0621,a12736a47c9e8f20c863bff8c35fa7db2d79875e5812f419799da2e8ec7cd41e"

    http {
        enabled = true
        port = 8080
        bind = "0.0.0.0"
        cors = true
        timeout = 5
    }

    whitelist {
        enabled = true
        pubkeys = "6b5008a293291c14effeb0e8b7c56a80ecb5ca7b801768e17ec93092be6c0621,a12736a47c9e8f20c863bff8c35fa7db2d79875e5812f419799da2e8ec7cd41e"
    }

    ratelimit {
        enabled = true
        perIpPerMinute = 300
        perPubkeyPerMinute = 500
        globalPerMinute = 5000
        burstMultiplier = "2.0"
        cleanupIntervalSeconds = 60
    }
}

db = "./strfry-db"

events {
    maxEventSize = 65536
}